### ISSUE TITLE
Remove un-needed elements

### ISSUE THREAD

**Issue by shaunbent** [beckytrav/build-page#1]
We've got a few extra elements in your HTML that don't do anything so we could remove them to clean things up a little.
#### `<div class="whole">`

You have a `<div class="whole">` which wraps everything in your page. This is actually invalid code, you can only add things like `<div>`s, `<sections>`s, `<p>`'s etc within the `<body>` element. 

There are only two valid elements which can go within the `<html>` element. These are `<head>` and `<body>`. Everything else has to go within these two tags.

https://github.com/beckytrav/build-page/blob/gh-pages/index.html#L3
#### Header `<div>`

There is a `<div>` wrapping the title of the page that doesn't do anything, we could remove this:
https://github.com/beckytrav/build-page/blob/gh-pages/index.html#L16

**Comment by beckytrav** [comment]
Removed the <div class="whole"> and the header <div>
