### ISSUE TITLE
Site title

### ISSUE THREAD

**Issue by shaunbent** [beckytrav/build-page#10]
Found a few elements that don't do anything:

https://github.com/beckytrav/build-page/blob/gh-pages/assets/_bodyheader.scss#L31
https://github.com/beckytrav/build-page/blob/gh-pages/assets/_bodyheader.scss#L26
https://github.com/beckytrav/build-page/blob/gh-pages/assets/_bodyheader.scss#L29
https://github.com/beckytrav/build-page/blob/gh-pages/assets/_bodyheader.scss#L28

You've got a double dash on the `site--title` class, double dashes are used to identify things that are modifiers. This site title isn't a modifier so it should be just `site-title`.

When building stuff try to think about how it might change in the future. For example right now the site title just has the word "Sport" but this might change in the future, we might add a button in here, or some other text. We want to build components so that if we change or add to them in the future we don't need to refactor it.

Right now you're half spacing the yellow bar using styles on `.site-title` and half using styles on `.site-title h1`. Try to move all the `padding` onto the `.site-title` so that we've created a space where we could drop any content and it would still be spaced consistently. Hola if you want me to explain that.

**Comment by beckytrav** [comment]
removed elements that don't do anything, amended site--title class to site-title, combined h1 and site-title paddings into site-title class
