### ISSUE TITLE
Validation errors

### ISSUE THREAD

**Issue by shaunbent** [beckytrav/build-page#2]
We've spoken before about there being a set of rules/guidlines for writing HTML that you need to pass. This is called validation. You can put a link to your website into a system and it will tell you if you've got any errors.

https://validator.w3.org/check?uri=beckytrav.github.io%2Fbuild-page&charset=%28detect+automatically%29&doctype=Inline&group=0

You've currently got 20 errors in your code. Resolve the issue #1 might fix some of these so do that first and then run it back through the validator.

**Comment by beckytrav** [comment]
checked the code against the validator after amending all issues raised, 0 errors found
