### ISSUE TITLE
Setting defaults, un-needed CSS rules

### ISSUE THREAD

**Issue by shaunbent** [beckytrav/build-page#5]
The `.grid` class has two rules set:

``` css
.grid {
    margin: auto;
    width: 100%;
}
```

You're using the `.grid` class on a `<div>` element. All element has a number of default styles that they always have. One of which is: `width: 100%;` another is: `margin: auto;`. So this rule isn't really doing anything so it could be removed.

If we're removing the CSS rule we could also remove the `<div>` from the HTML so clean that us as well.

https://github.com/beckytrav/build-page/blob/gh-pages/assets/main.css#L63-L66

**Comment by shaunbent** [comment]
I've just noticed that the rule below is also the same:

https://github.com/beckytrav/build-page/blob/gh-pages/assets/main.css#L67-L70

You've created a rule that sets the defaults on a element.

**Comment by shaunbent** [comment]
Same here: https://github.com/beckytrav/build-page/blob/gh-pages/assets/main.css#L78

`width: 100%;` is not needed

**Comment by shaunbent** [comment]
And here: https://github.com/beckytrav/build-page/blob/gh-pages/assets/main.css#L104

`height: auto;` is the default value so we don't need to explicitly state it.

**Comment by shaunbent** [comment]
And here: https://github.com/beckytrav/build-page/blob/gh-pages/assets/main.css#L146

I suppose you can go through the other stylesheet and find any more `width: 100%;`s and remove them if they're not needed.

**Comment by beckytrav** [comment]
removed all width: 100%;
