### ISSUE TITLE
Remove `article--move` classes

### ISSUE THREAD

**Issue by shaunbent** [beckytrav/build-page#7]
You're using the `article--move` classes to fix the grid and make everything align nicely. The problem with this is that we'd have to keep adding these classes every time we need to use the grid.

We can build a grid in a better way so that we don't need these classes. The trick is to use negative `margin` to create your grid (clever shit). Here are a few article that explain it, sorry if they're a little too detailed:
- http://csswizardry.com/2011/08/building-better-grid-systems/
- http://www.helloerik.com/the-subtle-magic-behind-why-the-bootstrap-3-grid-works

The idea is that your `row` element should have negative `margin-left`, then each `article` should have `padding-left` to create the gutter.

When fixing this issue create a new branch, do you work on this branch and then lets open a Pull Request so I can review the work there - have ago at your first PR.

**Comment by beckytrav** [comment]
Removed article--move classes.
Amended row, article grid and article to create the gutters.
Created a pull request branch grid-layout.
